create_token:
  fields:
    username:
      required: true
      selector:
        text: {}
    token_name:
      selector:
        text: {}
    expiration_duration:
      example: "12h"
      selector:
        text: {}
    expiration_date:
      selector:
        datetime: {}
    start_date:
      selector:
        datetime: {}
    dashboard:
      default: "lovelace"
      example: "lovelace-guest"
      selector:
        text: {}
    access_entity_id:
      example: "input_boolean.guest_access"
      selector:
        entity:
          domain:
            - schedule
            - input_boolean
    schedule_entity_id:
      example: "schedule.guest_access"
      selector:
        entity:
          domain: schedule
